### ISSUE TITLE
What is Codebar's complaint policy?

### ISSUE THREAD

**Issue by NataliaLKB** [foundersandcoders/london-membership#23]
Hey @sofer @claireinez! I finally completed this action. 

### TL:DR
No formal process

### Long answer

They tend to work on a case by case basis. They discuss between the organisers whether or not to warn a person, or ban them completely. Once that is decided they send them a formal email explaining that their account has been suspended.

... So their need is very different from ours anyway, but its good to be aware of what other people do

**Comment by claireinez** [comment]
Nice work @NataliaLKB! :tada:

**Comment by markwilliamfirth** [comment]
https://codebar.io/code-of-conduct
