### ISSUE TITLE
What is membership?

### ISSUE THREAD

**Issue by NataliaLKB** [foundersandcoders/london-membership#3]
This question needs to be answered in the readme of this doc. 

^ We forgot to assign someone to this action as the meeting

**Comment by NataliaLKB** [comment]
@sofer would you be able to start this off?

**Comment by NataliaLKB** [comment]
We should also link to this from the master reference repo

**Comment by sofer** [comment]
**What is membership?** Founders & Coders C.I.C. is a membership-based organisation, as laid out in our Articles of Association. Members *"may, by special resolution, direct the Directors to take, or refrain from taking, any specific action"*. Members have a right to vote at any general meeting of the company.

**How do you become a member?** By being the subscribers to the original Memorandum (in this case, it was @sofer @izaakrogan @besarthoxhaj) or by being voted in as a member at a general meeting.

**What about associate members?** Let's hold off on that for now.

**Comment by NataliaLKB** [comment]
> By being the subscribers to the original Memorandum (in this case, it was @sofer @izaakrogan @besarthoxhaj

I seem to remember when we became a C.I.C. and there was significantly more members that just you three 😕

**Comment by izaakrogan** [comment]
@NataliaLKB don't be offended! If I remember correctly, me and @besarthoxhaj were around when @sofer was sorting out the paperwork for the C.I.C. and he just needed a couple of signatures to get the ball rolling.

**Comment by NataliaLKB** [comment]
@izaakrogan offended? 

In the meeting where we decided that Ines and Dan would be directors, we also decided that the rest of us would be members. I am disappointed that the decision was not reflected in the official documents but there isn't much to be done about that now.

**Comment by NataliaLKB** [comment]
But regardless, this isn't at all what this issue is about 😂 . [This comment](https://github.com/foundersandcoders/london-membership/issues/3#issuecomment-296373540) was decided to be a bit off track and I finished off this issue with this PR: https://github.com/foundersandcoders/london-membership/pull/41
