### ISSUE TITLE
Ownership / membership of the foundersandcoders github org

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/london-membership#38]
Prompted by
[@mantagen's request to change a gitter channel name](https://github.com/gitterHQ/gitter/issues/1683)

![image](https://cloud.githubusercontent.com/assets/15656538/25274432/ec23764c-2687-11e7-90e7-4be74329c9f1.png)

I'm an owner of the `foundersandcoders` organisation, purely because of [my involvement in course coordination](https://github.com/foundersandcoders/master-reference/issues/133). I don't know whether I am allowed to, or should be allowed to, extend ownership to other people? Who is / isn't allowed to be an owner and why?

Current owners:
+ @besarthoxhaj 
+ @bradreeder 
+ @des-des 
+ @hdrdavies 
+ @iteles 
+ @izaakrogan 
+ @jsms90
+ @marisid 
+ @NataliaLKB 
+ @nelsonic 
+ @rebeccaradding 
+ @rjmk 
+ @rub1e 
+ @sofer 

Clarity please? :smile:

**Comment by claireinez** [comment]
@jsms90 We discussed this issue at our membership committee meeting today and came to the conclusion that as this is to do with the foundersandcoders organisation as a whole, this issue should not be raised in a London-specific repo. Perhaps [master-reference](https://github.com/foundersandcoders/master-reference) would be more appropriate for discussion so that all campuses can refer to the issue?

**Comment by des-des** [comment]
@claireinez @jsms90 maybe here: https://github.com/foundersandcoders/international

**Comment by NataliaLKB** [comment]
@jsms90 closing this issue here, would you be able to reopen in one of the above repos?

**Comment by rjmk** [comment]
I was going to wait for a further issue has been opened, but I'm worried I'll miss it.

Would someone remove me as an owner? I'm not currently involved enough to be able to say I'm fulfilling any associated responsibilities and I can't remove myself.

**Comment by NataliaLKB** [comment]
@rjmk I have made you a member, not an owner. Hopefully that works!

**Comment by rjmk** [comment]
Perfect, thanks! :)
