### ISSUE TITLE
Write up form for applying to membership

### ISSUE THREAD

**Issue by NataliaLKB** [foundersandcoders/london-membership#4]
As discussed in our first meeting.

This form could contain:
* Name
* Current email address
* Cohort (optional)

This form will also have to be sent to all our alumni asking them to register

**Comment by claireinez** [comment]
I'm on it :smiley:

**Comment by rebeccaradding** [comment]
@claireinez @NataliaLKB where are you with the membership form? Most of the Nazareth students are now eligible to apply for membership, as they've had two business meetings. I'd like to send out this form to them at some point in the next couple of weeks.

**Comment by NataliaLKB** [comment]
This has now been done!
