### ISSUE TITLE
Agenda April 24th 2017

### ISSUE THREAD

**Issue by NataliaLKB** [foundersandcoders/london-membership#40]
**Chairing/Minutes**:
**Attending:**

## Agenda:
* Actions from this past meeting https://github.com/foundersandcoders/london-membership/blob/master/minutes/29-03-2017.md
* What is membership? https://github.com/foundersandcoders/london-membership/issues/3
* PR template instead of google form? https://github.com/foundersandcoders/london-membership/issues/37
* Ownership of the github org https://github.com/foundersandcoders/london-membership/issues/38
* Define associate/Secondary membership. What does this mean?
* Discuss storing data policy
* Is our policy working so far? General check in

**Comment by sofer** [comment]
## Minutes
* Actions from this past meeting 
* What is membership? @NataliaLKB to pick this one up
* PR template instead of google form? AGREED
* Ownership of the github org 
* Define associate/Secondary membership. 
* Discuss storing data policy
* Is our policy working so far?
