### ISSUE TITLE
Create a minutes .md file for our last meeting 

### ISSUE THREAD

**Issue by NataliaLKB** [foundersandcoders/london-membership#42]
Don't forget to do this! 

It doesn't look like we have the full minutes in #40

**Comment by sofer** [comment]
@NataliaLKB those were the minutes I took. What have you spotted that I have left out?

**Comment by NataliaLKB** [comment]
@sofer I guess I feel like we discussed a lot more and the actions have been recorded, but not the discussion (also useful). I don't remember anything anymore though - its been too long 😆
