### ISSUE TITLE
Membership criteria review

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/london-membership#52]
Modification of proposal made in `london-programme`off basis of discussion: https://github.com/foundersandcoders/london-programme/issues/239

## Why

If you can't attend an early business meeting, students are not legible to become members until the last month of their cohort. This has meant we're now at the end of FAC10 and many students are not members.

Despite this by virtue of being in the space, leading business task groups, organising graduate projects, planning the next curriculum, contributing to our resources, running our meetups, etc, students are active contributors in the community. Current criteria limits their engagement at the most active period of their participation in the campus.

## What

Change membership criteria to having attended one business meeting and have been a student for 8 weeks. My understanding is that the current criteria was decided so that:

* Members have attended business meetings to get experience of how they are conducted.
* There is a guarantee that members have been active in our community and become familiarised with how it works for a few months.
* There is enough time to identify anyone who might violate our code of conduct.

The proposed change would still accomplish this while helping to solve some of the problems identified here (and in the `london-programme` issue).

**Comment by NataliaLKB** [comment]
Hello @bradreeder ! Thanks for posting this issue.

We have chatted and we realise we haven't trialled the current membership criteria long enough to establish a need for a change. 

I am going to close this issue for now, but if this creates problems please reopen with specific examples. 

Thanks!
Natalia, Claire & Dan
