### ISSUE TITLE
Agenda 7th June 2017

### ISSUE THREAD

**Issue by claireinez** [foundersandcoders/london-membership#55]
#**Chairing/Minutes:**
**Attending:**

## Agenda:

+ Actions from [this past meeting](https://github.com/foundersandcoders/london-membership/blob/master/minutes/24-04-2017.md)
- [x] Merge [pull requests](https://github.com/foundersandcoders/london-membership/pulls) approved in the business meeting
- [x] Merge any outstanding PRs related to this repo #48 #58
+ Discuss storing data policy #10 
+ Membership criteria review #52 
+ Is our policy working so far? General check in and confirm process for new cohorts starting soon
+ AOB

**Comment by claireinez** [comment]
Meeting postponed until @sofer is back in the country and I don't have such a terrible hangouts connection :laughing:

**Comment by sofer** [comment]
I am back on Monday.
