### ISSUE TITLE
Membership Criteria Possibly Stated Incorrectly in London Membership doc

### ISSUE THREAD

**Issue by BartBucknill** [foundersandcoders/london-membership#59]
During FAC11 first day we were informed that application for voting membership required attendance at 2 business meetings. The London Membership doc adds that applicants for voting membership should be "**programme graduates**, who have attended two business meetings" (emphasis added). The doc further requires that the cohort from which the applicant graduated be stated as part of the voting membership application. 

#52, whilst calling for a wider review of voting membership application criteria, also implies that the current requirement is attendance of 2 business meetings, and not graduation.

If graduation is not in fact a requirement, and application is actually open to members of the current cohort who have attended two business meetings, we should change this doc.

**Comment by claireinez** [comment]
Nice catch @BartBucknill! You are correct -- graduation is not a requirement and current course participants can indeed apply for membership, providing they satisfy the requirement of having attended two business meetings. I will update the documentation and Pull Request template appropriately :smiley:
