### ISSUE TITLE
Are members of other FAC communities allowed to vote?

### ISSUE THREAD

**Issue by claireinez** [foundersandcoders/london-membership#64]
FAC is growing worldwide and I was wondering if someone is a member of another FAC community, are they allowed to vote at a London business meeting? Would they have to apply for membership in London and, if so, would they be eligible for full membership given they did not graduate from London?

**Comment by rebeccaradding** [comment]
In Nazareth, the community decided that once a member of another campus had attended two business meetings, they could apply for membership in FAC Nazareth. It would make sense for the policies to be similar, though, and I'm sure Nazareth would revisit the issue if London would prefer a different policy.

**Comment by claireinez** [comment]
That's actually what I was going to suggest; I wasn't aware Nazareth had already handled it!

**Comment by claireinez** [comment]
I'll close this now and we can follow the path @rebeccaradding mentioned is being followed in Nazareth. We can open again and discuss if we need to in the future.
