### ISSUE TITLE
Draft membership application form

### ISSUE THREAD

**Issue by claireinez** [foundersandcoders/london-membership#9]
I have put together a basic application form here:
https://goo.gl/forms/ZzSBYw8Rm5X5laQ42

@sofer and @NataliaLKB have I missed anything?

**Comment by NataliaLKB** [comment]
Looks good to me!

**Comment by rebeccaradding** [comment]
@claireinez is this live yet?

Can I suggest that you call it "Founders & Coders London Application Form," as I'm going to copy the form and rename it for use in Nazareth...thanks!

**Comment by claireinez** [comment]
Good point @rebeccaradding! I'll make that change and make it live before the end of the week.

**Comment by NataliaLKB** [comment]
@rebeccaradding Hey! Just letting you know we have changed the wording slightly, and are sending it out this evening. No major changes though!

**Comment by NataliaLKB** [comment]
This has now been sent out. Feel free to open issues regarding amendments
